### ISSUE TITLE
matrix_simd.hpp missing

### ISSUE THREAD

**Issue by davidlatwe** [ChaosGroup/vray_al_surface#10]
Sorry, Where can I find this matrix_simd.hpp ?
I tried to compile the latest commit but failed.

**Comment by vkoylazov** [comment]
You need a newer version of V-Ray which includes the file.

Best regards,
Vlado

**Comment by davidlatwe** [comment]
Thank you for the reply.
I have found it from the latest trial version.

Thanks again.
